version: 0.2

phases:
  build:
    commands:
      - echo Build started
      - mvn clean install
      - aws s3 rm s3://test-123-arya/src --recursive
#      - aws s3 rm s3://final-test-priyanshi/order-service.jar

  post_build:
    commands:
      - echo Build completed successfull.
artifacts:
  files:
    - target/arya.jar
  discard-paths: yes