version: 0.2

phases:
  build:
    commands:
      - echo Build started
      - mvn clean install
      - aws s3 rm s3://final-test-priyanshi/src --recursive

  post_build:
    commands:
      - echo Build completed Successfully.
artifacts:
  files:
    - target/arya.jar
  discard-paths: yes